#!/bin/bash 
### BEGIN INIT INFO
# Provides:             surealived
# Required-Start:       $network $local_fs $remote_fs
# Required-Stop:        $network $local_fs $remote_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    SureAliveD - effective LVS service tester
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/surealived
NAME=surealived
DESC=surealived
DEFAULT=/etc/default/surealived

# default settings
CHECKER_CONFIG=/etc/surealived/services.xml
AUTOSTART=false

DIFFS=/var/lib/surealived/diffs
STATS=/var/lib/surealived/stats
COMM=/var/lib/surealived/comm

#create /var/lib/surealived subdirectory ( used if /var/lib/surealived is tmpfs mount )
mkdir -p $DIFFS $STATS $COMM

# check for config
test -r "$DEFAULT" && . "$DEFAULT"

TEST="$DAEMON -t $CHECKER_CONFIG"
RUN="$DAEMON -d $CHECKER_CONFIG"

if [ ! -f "$CHECKER_CONFIG" ]; then
    echo "No configuration file: $CHECKER_CONFIG (check /usr/share/doc/surealived/examples)"
    exit 0
fi
if [ ! -f "$CONFIG" ]; then
    echo "No surealived's config file: $CONFIG"
    exit 0
fi
if [ ! -f "$DAEMON" ]; then
    echo "No executable: $DAEMON"
    exit 0
fi

#ulimit -n $MAXFD
case "$1" in
  start)
        if [ "$AUTOSTART" != "true" ] && [ ! -z "$RUNLEVEL" ]; then     # runlevel!=NULL at system startup
            echo "Not starting surealived tester - check $DEFAULT"
            exit 0;
        fi

       echo -n "Testing if surealived isn't running:    "
       pgrep -f $DAEMON 1>/dev/null
       if [ $? -eq 0 ]; then
          echo "FAIL"
          echo "surealived pids: "
          pgrep -f $DAEMON
          exit 1
       fi
       echo "OK"
       
       echo -n "Starting $DESC:    "
       $TEST 2>/tmp/sdstartup.log && $RUN
       if [ $? -eq 0 ]; then
          echo "OK"
	  sleep 1
       else 
	  echo "FAIL"
          echo "=== log error ==="
	  cat /tmp/sdstartup.log
	  rm /tmp/sdstartup.log	  
       fi
       ;;
  stop)
       echo -n "Stopping $DESC:    "
       pkill -INT -f $DAEMON
       if [ $? -eq 0 ]; then
          echo "OK"
       else 
          echo "FAIL"
       fi
       ;;

  reload|force-reload)
       echo -n "Reloading $DESC:    "
       pkill -HUP -f $DAEMON
       if [ $? -eq 0 ]; then
          echo "OK"
       else 
          echo "FAIL"
       fi
       ;;
  restart)
       echo -n "Restarting $DESC:    "
       pkill -TERM -f $DAEMON
       if [ $? -eq 0 ]; then
	   echo "OK"
       else
	   echo "FAIL"
       fi
       ;;

  *)
       echo "Usage: /etc/init.d/$NAME-check {start|stop|restart|reload|force-reload}" >&2
       exit 1
       ;;
esac

exit 0
